apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: user-management
data:
  FLASK_ENV: "production"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  RABBITMQ_VHOST: "/"
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"