apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: user-management
type: Opaque
stringData:
  MAILERSEND_API_TOKEN: ${MAILERSEND_API_TOKEN}
  SENDER_EMAIL: ${SENDER_EMAIL}
  SENDER_NAME: User Management System
  RABBITMQ_USER: guest
  RABBITMQ_PASSWORD: guest
