apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: user-management
type: OpaquestringData:
  RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
  RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
