apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: user-management
type: OpaquestringData:
  POSTGRES_PASSWORD: master  # From ${POSTGRES_PASSWORD}
  POSTGRES_USER: davit       # From ${POSTGRES_USER}
  POSTGRES_DB: db2025        # From ${POSTGRES_DB}
